export type Employee = {
  user_id: number;
  employee_code: string;
  user_name: string;
  user_email: string;
  full_name: string;
  date_of_birth: string;
  gender: string;
  age: number;
  current_address: string;
  permanent_address: string;
  mobile: string;
  personal_mail: string;
  emergency_contact_name: string;
  emergency_contact_mobile: string;
  company_mail: string;
  office_phone: string;
  city: string;
  office_address: string;
  professional_reporting_manager: string;
  hr_name: string;
  employment_history: string;
  date_of_joining: string;
  project_code: string;
  project_start_date: string;
  project_end_date: string | null;
  client_name: string;
  project_reporting_manager: string;
  pancard: string;
  aadharcard: string;
  bank_name: string;
  branch: string;
  ifsc_code: string;
  ctc_breakup: string;
};
